import sys
sys.path.insert(0, r'C:\Users\joshk\pine-bridge')

from fpdf import FPDF
from config import KNOWN_APPS

class CommandPDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 24)
        self.set_text_color(0, 102, 204)
        self.cell(0, 15, 'Pine Bridge Voice Assistant', ln=True, align='C')
        self.set_font('Helvetica', '', 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, 'Complete Command Reference Guide', ln=True, align='C')
        self.ln(5)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', align='C')
        
    def section_title(self, title, emoji=''):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(0, 51, 102)
        self.set_fill_color(230, 240, 250)
        self.cell(0, 10, f'  {title}', ln=True, fill=True)
        self.ln(3)
        
    def command_row(self, command, description, example=''):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(0, 0, 0)
        self.cell(80, 6, f'  "{command}"', ln=False)
        self.set_font('Helvetica', '', 10)
        self.set_text_color(60, 60, 60)
        self.cell(0, 6, description, ln=True)
        if example:
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(100, 100, 100)
            self.cell(80, 5, '', ln=False)
            self.cell(0, 5, f'Example: {example}', ln=True)
        self.ln(1)

pdf = CommandPDF()
pdf.alias_nb_pages()
pdf.set_auto_page_break(auto=True, margin=20)

# Page 1: Overview
pdf.add_page()
pdf.set_font('Helvetica', 'B', 14)
pdf.set_text_color(0, 0, 0)
pdf.cell(0, 10, 'How to Use', ln=True)
pdf.set_font('Helvetica', '', 11)
pdf.multi_cell(0, 6, 
    '1. Hold Ctrl+Alt to activate push-to-talk\n'
    '2. Speak your command clearly\n'
    '3. Release keys when done speaking\n'
    '4. Pine Bridge will respond with voice + text\n\n'
    'The microphone heartbeat shows when audio is being captured:\n'
    '  - Silent: MIC all grey (no sound)\n'
    '  - Speaking: MIC with green/yellow/red bars\n'
    '  - Loud: MIC with red bars')
pdf.ln(5)

# Page 2: System Commands
pdf.add_page()
pdf.section_title('System Commands')

pdf.command_row('shutdown', 'Shut down the computer')
pdf.command_row('restart', 'Restart the computer')
pdf.command_row('reboot', 'Restart the computer')
pdf.command_row('lock', 'Lock the screen')
pdf.command_row('sleep', 'Put computer to sleep')
pdf.command_row('hibernate', 'Hibernate the computer')
pdf.command_row('cancel shutdown', 'Cancel pending shutdown/restart')
pdf.command_row('screenshot', 'Take a screenshot (saves to Desktop)')
pdf.command_row('take a screenshot', 'Take a screenshot')
pdf.ln(3)

pdf.section_title('Volume & Audio')
pdf.command_row('volume up', 'Increase volume by 10%')
pdf.command_row('volume down', 'Decrease volume by 10%')
pdf.command_row('set volume to 50', 'Set volume to specific level (0-100)', 'set volume to 75')
pdf.command_row('what is the volume', 'Get current volume level')
pdf.command_row('mute', 'Mute all audio')
pdf.command_row('unmute', 'Unmute audio')
pdf.ln(3)

pdf.section_title('Brightness')
pdf.command_row('brightness up', 'Increase screen brightness')
pdf.command_row('increase brightness', 'Increase screen brightness')
pdf.command_row('brightness down', 'Decrease screen brightness')
pdf.command_row('decrease brightness', 'Decrease screen brightness')
pdf.ln(3)

pdf.section_title('Media Control')
pdf.command_row('next track', 'Play next track/song')
pdf.command_row('next song', 'Play next track/song')
pdf.command_row('previous track', 'Play previous track/song')
pdf.command_row('previous song', 'Play previous track/song')
pdf.command_row('play', 'Play/Pause media')
pdf.command_row('pause', 'Play/Pause media')
pdf.command_row('toggle', 'Play/Pause media')

# Page 3: App Commands
pdf.add_page()
pdf.section_title('Open Applications (A-C)')
pdf.command_row('open chrome', 'Open Google Chrome')
pdf.command_row('open brave', 'Open Brave Browser')
pdf.command_row('open edge', 'Open Microsoft Edge')
pdf.command_row('open firefox', 'Open Mozilla Firefox')
pdf.command_row('open calculator', 'Open Calculator')
pdf.command_row('open notepad', 'Open Notepad')
pdf.command_row('open paint', 'Open Paint')
pdf.command_row('open cmd', 'Open Command Prompt')
pdf.command_row('open command prompt', 'Open Command Prompt')
pdf.command_row('open powershell', 'Open PowerShell')
pdf.command_row('open terminal', 'Open Windows Terminal')
pdf.command_row('open file explorer', 'Open File Explorer')
pdf.command_row('open explorer', 'Open File Explorer')
pdf.command_row('open claude', 'Open Claude')
pdf.command_row('open cursor', 'Open Cursor IDE')
pdf.ln(3)

pdf.section_title('Open Applications (D-F)')
pdf.command_row('open discord', 'Open Discord')
pdf.command_row('open docker', 'Open Docker Desktop')
pdf.command_row('open excel', 'Open Microsoft Excel')
pdf.command_row('open excel 2016', 'Open Microsoft Excel 2016')
pdf.command_row('open git bash', 'Open Git Bash')
pdf.command_row('open git gui', 'Open Git GUI')
pdf.ln(3)

pdf.section_title('Open Applications (G-M)')
pdf.command_row('open google chrome', 'Open Google Chrome')
pdf.command_row('open maltego', 'Open Maltego')
pdf.command_row('open metaeditor', 'Open MetaEditor')
pdf.command_row('open metatrader', 'Open MetaTrader 5')
pdf.command_row('open metatrader 5', 'Open MetaTrader 5')
pdf.command_row('open node', 'Open Node.js')
pdf.command_row('open node js', 'Open Node.js')
pdf.command_row('open onenote', 'Open Microsoft OneNote')
pdf.command_row('open outlook', 'Open Microsoft Outlook')
pdf.command_row('open powerpoint', 'Open Microsoft PowerPoint')
pdf.command_row('open python', 'Open Python')
pdf.ln(3)

pdf.section_title('Open Applications (R-Z)')
pdf.command_row('open registry editor', 'Open Registry Editor')
pdf.command_row('open remote desktop', 'Open Remote Desktop')
pdf.command_row('open settings', 'Open Windows Settings')
pdf.command_row('open snipping tool', 'Open Snipping Tool')
pdf.command_row('open spotify', 'Open Spotify')
pdf.command_row('open task manager', 'Open Task Manager')
pdf.command_row('open vlc', 'Open VLC Media Player')
pdf.command_row('open vscode', 'Open Visual Studio Code')
pdf.command_row('open visual studio code', 'Open Visual Studio Code')
pdf.command_row('open word', 'Open Microsoft Word')
pdf.command_row('open word 2016', 'Open Microsoft Word 2016')
pdf.command_row('open zoom', 'Open Zoom')
pdf.command_row('open anydesk', 'Open AnyDesk')
pdf.ln(3)

pdf.section_title('Close Applications')
pdf.command_row('close chrome', 'Close Google Chrome')
pdf.command_row('close firefox', 'Close Mozilla Firefox')
pdf.command_row('close notepad', 'Close Notepad')
pdf.command_row('close spotify', 'Close Spotify')
pdf.command_row('close discord', 'Close Discord')
pdf.command_row('close excel', 'Close Microsoft Excel')
pdf.command_row('close word', 'Close Microsoft Word')
pdf.command_row('close powerpoint', 'Close Microsoft PowerPoint')

# Page 4: Web Commands
pdf.add_page()
pdf.section_title('Web Search')
pdf.command_row('search for python tutorials', 'Search Google for query', 'search for machine learning')
pdf.command_row('google python tutorials', 'Search Google for query', 'google weather today')
pdf.command_row('search machine learning', 'Search Google for query')
pdf.ln(3)

pdf.section_title('Open Websites')
pdf.command_row('go to github', 'Open GitHub')
pdf.command_row('go to reddit', 'Open Reddit')
pdf.command_row('go to youtube', 'Open YouTube')
pdf.command_row('go to amazon', 'Open Amazon')
pdf.command_row('go to linkedin', 'Open LinkedIn')
pdf.command_row('go to twitter', 'Open Twitter/X')
pdf.command_row('go to facebook', 'Open Facebook')
pdf.command_row('go to instagram', 'Open Instagram')
pdf.command_row('go to wikipedia', 'Open Wikipedia')
pdf.command_row('go to netflix', 'Open Netflix')
pdf.command_row('go to stackoverflow', 'Open Stack Overflow')
pdf.command_row('go to tradingview', 'Open TradingView')
pdf.command_row('go to notion', 'Open Notion')
pdf.command_row('go to figma', 'Open Figma')
pdf.command_row('go to trello', 'Open Trello')
pdf.command_row('go to medium', 'Open Medium')
pdf.command_row('go to dev.to', 'Open Dev.to')
pdf.command_row('go to chatgpt', 'Open ChatGPT')
pdf.command_row('go to claude', 'Open Claude AI')
pdf.command_row('go to deepseek', 'Open DeepSeek')
pdf.command_row('go to perplexity', 'Open Perplexity')
pdf.command_row('go to gemini', 'Open Google Gemini')
pdf.command_row('go to copilot', 'Open Microsoft Copilot')
pdf.command_row('go to yahoo finance', 'Open Yahoo Finance')
pdf.command_row('go to coinmarketcap', 'Open CoinMarketCap')
pdf.command_row('go to coinbase', 'Open Coinbase')
pdf.command_row('go to binance', 'Open Binance')
pdf.ln(3)

pdf.section_title('Web Apps (Chrome)')
pdf.command_row('open gmail', 'Open Gmail in Chrome')
pdf.command_row('open email', 'Open Gmail in Chrome')
pdf.command_row('open mail', 'Open Gmail in Chrome')
pdf.command_row('open youtube for music', 'Search YouTube for music', 'open youtube for jazz')
pdf.command_row('open whatsapp', 'Open WhatsApp Web in Chrome')
pdf.command_row('open telegram', 'Open Telegram Web in Chrome')
pdf.command_row('open discord in chrome', 'Open Discord in Chrome')
pdf.command_row('open google docs', 'Open Google Docs')
pdf.command_row('open google drive', 'Open Google Drive')
pdf.command_row('open google classroom', 'Open Google Classroom')
pdf.command_row('open google maps', 'Open Google Maps')
pdf.command_row('open maps', 'Open Google Maps')
pdf.command_row('open zoom meeting', 'Open Zoom Meeting')
pdf.command_row('open outlook web', 'Open Outlook Web')
pdf.command_row('open onedrive', 'Open OneDrive Web')
pdf.command_row('browse reddit', 'Open Reddit in Chrome')
pdf.command_row('navigate to amazon', 'Open Amazon in Chrome')
pdf.command_row('visit linkedin', 'Open LinkedIn in Chrome')
pdf.command_row('open tradingview', 'Open TradingView in Chrome')

# Page 5: File Commands
pdf.add_page()
pdf.section_title('File Operations')
pdf.command_row('list files on desktop', 'List files on Desktop')
pdf.command_row('list files in documents', 'List files in Documents folder', 'list files in downloads')
pdf.command_row('create folder called Projects', 'Create a new folder on Desktop', 'create folder called Work')
pdf.command_row('create file called notes.txt', 'Create a new file on Desktop', 'create file called todo.txt')
pdf.command_row('open file notes.txt', 'Open a specific file', 'open file report.pdf')
pdf.command_row('delete old_file.txt', 'Delete a file', 'delete temp.docx')
pdf.command_row('find document.pdf', 'Search for files', 'find presentation.pptx')
pdf.command_row('search for files report', 'Search for files by name', 'search for files budget')
pdf.ln(3)

pdf.section_title('Time & Date')
pdf.command_row('what time is it', 'Get current time')
pdf.command_row('what is the time', 'Get current time')
pdf.command_row('tell me the time', 'Get current time')
pdf.command_row('what date is it', 'Get today\'s date')
pdf.command_row('what is the date', 'Get today\'s date')
pdf.command_row('what day is it', 'Get day of week')
pdf.command_row('what is the day', 'Get day of week')
pdf.ln(3)

pdf.section_title('Calculator')
pdf.command_row('calculate 15 times 3', 'Calculate math expression', 'calculate 100 divided by 5')
pdf.command_row('compute 2 plus 2', 'Calculate math expression', 'compute 50 minus 10')
pdf.command_row('what is 2 plus 2', 'Calculate math expression', 'what is 10 to the power of 3')
pdf.ln(3)

pdf.section_title('System Information')
pdf.command_row('system info', 'Get system information')
pdf.command_row('about this computer', 'Get system information')
pdf.command_row('about this pc', 'Get system information')
pdf.ln(3)

pdf.section_title('Chat & Greetings')
pdf.command_row('hello', 'Greet the assistant')
pdf.command_row('hi', 'Greet the assistant')
pdf.command_row('hey', 'Greet the assistant')
pdf.command_row('good morning', 'Greet the assistant')
pdf.command_row('how are you', 'Ask how assistant is doing')
pdf.command_row('who are you', 'Ask about the assistant')
pdf.command_row('what is your name', 'Ask about the assistant')
pdf.command_row('thank you', 'Thank the assistant')
pdf.command_row('thanks', 'Thank the assistant')
pdf.command_row('bye', 'Say goodbye')
pdf.command_row('goodbye', 'Say goodbye')

# Save PDF
output_path = r'C:\Users\joshk\Desktop\Pine_Bridge_Commands.pdf'
pdf.output(output_path)
print(f'PDF saved to: {output_path}')
